os:
    - linux
language: node_js
node_js:
    - "8.10.0"
before_install:
    - npm install -g npm
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
install:
    - yarn install
    - yarn link
script:
    - yarn test
    - npm version patch -m "Bumping to %s"
    - git push --tags
deploy:
    provider: npm
    email: anoop2811@aol.in
    skip_cleanup: true
    api_key: $API_TOKEN
#    on:
#        tags: true

notifications:
    email:
        recipients:
        - anoop2811@aol.in
        on_success: change
        on_failure: always
